---
# tasks file for docker
- name: Install packages
  apt: name={{ item }} state=present update_cache=yes
  loop:
    - docker.io

- name: Create or update /etc/docker/daemon.json
  become: yes
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": [{{ registry_url }}]
      }
    force: yes

- name: Login docker
  docker_login:
    registry_url: "{{ registry_url }}"
    username: "{{ username }}"
    password: "{{ password }}"
