
---
- name: Build and push application docker image
  hosts: vm
  become: yes

  vars:
    dockerfile_path: /dockerfile

  roles:
    - role: docker
      registry_url: "{{ registry_url }}"
      username: "{{ username }}"
      password: "{{ password }}"

    - role: build
      repo_url: "{{ repo_url }}"
      dest_url: "{{ dest_url }}"

  tasks:
    - name: Create Dockerfile
      copy:
        dest: "{{ dockerfile_path }}"
        content: |
          FROM tomcat:9.0
          WORKDIR /usr/local/tomcat
          RUN rm -rf webapps/*
          COPY {{ war_file }} webapps/ROOT.war
          EXPOSE 8080
          CMD ["catalina.sh", "run"]

    - name: Build Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "/app/target"
          dockerfile: "{{ dockerfile_path }}"
        source: build
        state: present

    - name: Push Docker image to registry
      docker_image:
        name: "{{ docker_image_name }}"
        repository: "{{ registry_url }}/{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Logout Docker
      docker_login:
        state: absent
