
---
- name: Build and push application docker image
  hosts: vm
  become: yes

  vars:
    dest_dir: /app
    dockerfile_path: /dockerfile

  roles:
    - role: docker
      registry_url: "{{ registry_url }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Ensure git
      apt:
        name: git
        state: present

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: master

    - name: Build app inside Docker container
      docker_container:
        name: build_app
        image: maven:3.8.6-openjdk-8
        volumes:
          - "{{ dest_dir }}:/app"
        command: mvn clean package
        working_dir: /app
        state: started

    - name: Rename War File
      copy:
        remote_src: True
        dest: "{{ dest_dir }}/target/{{ war_file }}"
        src: "{{ dest_dir }}/target/app.war"

    - name: Copy Dockerfile
      copy:
        src: "{{ dockerfile }}"
        dest: "{{ dockerfile_path }}"

    - name: Build Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ dest_dir }}/target"
          dockerfile: "{{ dockerfile_path }}"
        source: build
        state: present

    - name: Push Docker image to registry
      docker_image:
        name: "{{ docker_image_name }}"
        repository: "{{ registry_url }}/{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Logout Docker
      docker_login:
        state: absent

    - name: Clean up Docker container
      docker_container:
        name: build_app
        state: absent
