
---
- name: Build and push application docker image
  hosts: vm
  become: yes

  vars:
    dest_dir: /app
    dockerfile_path: /dockerfile

  roles:
    - role: docker
      registry_url: "{{ registry_url }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Ensure Dependency
      apt: name={{ item }} state=present update_cache=yes
      loop:
        - git
        - openjdk-8-jdk
        - maven

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: master

    - name: Build App
      command: mvn clean package
      args:
        chdir: "{{ dest_dir }}"
      notify: fetch war file

    - name: Rename War File
      copy:
        remote_src: True
        dest: "{{ dest_dir }}/target/app.war"
        src: "{{ dest_dir }}/target/{{ war_file }}"

    - name: Copy Dockerfile
      copy:
        src: "{{ dockerfile }}"
        dest: "{{ dockerfile_path }}"

    - name: Build Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ dest_dir }}/target"
          dockerfile: "{{ dockerfile_path }}"
        source: build
        state: present

    - name: Push Docker image to registry
      docker_image:
        name: "{{ docker_image_name }}"
        repository: "{{ registry_url }}/{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    - name: Logout Docker
      docker_login:
        state: absent
