
---
- name: Build and push application docker image
  hosts: vm
  become: yes

  roles:
    - role: docker
      registry_url: "{{ registry_url }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Pull Docker image to registry
      docker_image:
        name: "{{ docker_image_name }}"
        repository: "{{ registry_url }}/{{ docker_image_name }}"
        tag: "{{ image_tag }}"
        pull: yes

    - name: Run Docker Image
      docker_container:
        name: "app"
        image: "{{ docker_image_name }}:{{ image_tag }}"
        state: started
        ports:
          - "{{ app_port }}:{{ 8080 }}"
        restart_policy: always

    - name: Logout Docker
      docker_login:
        state: absent
